[profile.release]
panic = 'unwind'

[workspace]
members = [
	"node",
	"runtime/mars",
	"runtime/template",
#	"runtime/odyssey",
]

#[patch."https://github.com/paritytech/substrate"]
#pallet-session = { git = "https://github.com/aresprotocols/ocw-suit", default-features = false, branch = "polkadot-v0.9.10" }